# Generated by Django 5.1.2 on 2024-12-09 11:50

from django.db import migrations

def populate_groups_and_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    manager_group, _ = Group.objects.create(name='Manager')
    vet_group, _ = Group.objects.create(name='Vet')

    manager_permissions = Permission.objects.filter(codename__in=[
        'change_customuser', 'delete_customuser', 'view_customuser',
        'change_profile', 'delete_profile', 'view_profile',
        'add_logentry', 'view_logentry',
        'add_image', 'change_image', 'delete_image', 'view_image',
        'add_medicine', 'change_medicine', 'view_medicine', 'delete_medicine',
        'add_service', 'change_service', 'view_service', 'delete_service',
        'add_servicecategory', 'change_servicecategory', 'view_servicecategory', 'delete_servicecategory',
    ])
    manager_group.permissions.add(manager_permissions)

    vet_permissions = Permission.objects.filter(codename__in=[
        'add_medicalreport', 'change_medicalreport', 'view_medicalreport', 'delete_medicalreport',
        'add_medicine', 'change_medicine', 'view_medicine', 'delete_medicine',
        'add_service', 'change_service', 'view_service', 'delete_service',
    ])
    vet_group.permissions.add(vet_permissions)

    manager_group.save()
    vet_group.save()


def remove_groups_and_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Manager', 'Veterinarian']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial_squashed_0004_alter_profile_city_alter_profile_country_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_groups_and_permissions, remove_groups_and_permissions),
    ]
