# Generated by Django 5.1.2 on 2024-11-29 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_is_vet_customuser_is_vet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Phone number should be exactly 10 characters long'), django.core.validators.RegexValidator('^[\\d]*$', 'Phone number should consist of digits only')], verbose_name='phone number'),
        ),
    ]
