# Generated by Django 5.1.2 on 2024-12-09 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('services', '0001_initial'), ('services', '0002_servicecategory_service_category'), ('services', '0003_alter_service_category'), ('services', '0004_alter_servicecategory_options_and_more'), ('services', '0005_service_name_bg_service_name_en'), ('services', '0006_service_description_bg_service_description_en'), ('services', '0007_medicine_description_bg_medicine_description_en'), ('services', '0008_alter_medicine_name_alter_service_name_and_more')]

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A category with that name already exists.'}, max_length=100, unique=True, verbose_name='name')),
                ('name_bg', models.CharField(error_messages={'unique': 'A category with that name already exists.'}, max_length=100, null=True, unique=True, verbose_name='name')),
                ('name_en', models.CharField(error_messages={'unique': 'A category with that name already exists.'}, max_length=100, null=True, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'Service categories',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A service with that name already exists.'}, max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('dosages', models.TextField(verbose_name='dosages')),
                ('reports', models.ManyToManyField(related_name='medicines', to='pets.medicalreport', verbose_name='reports')),
                ('description_bg', models.TextField(null=True, verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A service with that name already exists.'}, max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('reports', models.ManyToManyField(related_name='services', to='pets.medicalreport', verbose_name='reports')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_services', to='services.servicecategory', verbose_name='category')),
                ('name_bg', models.CharField(error_messages={'unique': 'A service with that name already exists.'}, max_length=100, null=True, unique=True, verbose_name='name')),
                ('name_en', models.CharField(error_messages={'unique': 'A service with that name already exists.'}, max_length=100, null=True, unique=True, verbose_name='name')),
                ('description_bg', models.TextField(null=True, verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
