# Generated by Django 5.1.2 on 2024-11-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('dosages', models.TextField(verbose_name='dosages')),
                ('reports', models.ManyToManyField(related_name='medicines', to='pets.medicalreport', verbose_name='reports')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('reports', models.ManyToManyField(related_name='services', to='pets.medicalreport', verbose_name='reports')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
