# Generated by Django 5.1.2 on 2024-12-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_name_bg_service_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_bg',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
