# Generated by Django 5.1.2 on 2024-12-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_description_bg_service_description_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='description_bg',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
