# Generated by Django 5.1.2 on 2024-12-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_medicine_description_bg_medicine_description_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(error_messages={'unique': 'A service with that name already exists.'}, max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(error_messages={'unique': 'A service with that name already exists.'}, max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_bg',
            field=models.CharField(error_messages={'unique': 'A service with that name already exists.'}, max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_en',
            field=models.CharField(error_messages={'unique': 'A service with that name already exists.'}, max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(error_messages={'unique': 'A category with that name already exists.'}, max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_bg',
            field=models.CharField(error_messages={'unique': 'A category with that name already exists.'}, max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(error_messages={'unique': 'A category with that name already exists.'}, max_length=100, null=True, unique=True, verbose_name='name'),
        ),
    ]
