# Generated by Django 5.1.2 on 2024-11-20 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_medicalreport_doctor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petstatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='petstatus',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status', serialize=False, to='pets.pet', verbose_name='pet'),
        ),
    ]
