# Generated by Django 5.1.2 on 2024-11-29 11:17

import VetClinic.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_medicalreport_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=50, validators=[VetClinic.validators.CapitalFirstLetterValidator()], verbose_name='name'),
        ),
    ]
