# Generated by Django 5.1.2 on 2024-11-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='doctors',
        ),
    ]
