# Generated by Django 5.1.2 on 2024-11-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_remove_petstatus_id_alter_petstatus_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
    ]
