# Generated by Django 5.1.2 on 2024-12-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_remove_pet_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('rodent', 'Rodent'), ('bird', 'Bird'), ('reptile', 'Reptile'), ('other', 'Other')], default='other', max_length=50, verbose_name='species'),
        ),
    ]
