# Generated by Django 5.1.2 on 2024-11-18 13:59

import VetClinic.images.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), VetClinic.images.validators.FileSizeValidator(3)], verbose_name='image')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='date uploaded')),
                ('category', models.CharField(choices=[('Carousel', 'Carousel'), ('Gallery', 'Gallery'), ('Other', 'Other')], default='Other', max_length=50, verbose_name='category')),
            ],
        ),
    ]
