# Generated by Django 5.1.2 on 2024-11-29 11:09

import VetClinic.images.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), VetClinic.images.validators.FileSizeValidator(3)], verbose_name='image'),
        ),
    ]
